// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfFkmvAgFZnwxLoT__61Y2CiF3CnqYLJ8',
    appId: '1:946653516976:web:794b6e858130eb3d311775',
    messagingSenderId: '946653516976',
    projectId: 'instaface-cfa00',
    authDomain: 'instaface-cfa00.firebaseapp.com',
    storageBucket: 'instaface-cfa00.appspot.com',
    measurementId: 'G-P0E0ZG593T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JmZzh7QUpMm8XVAF-Q8cfQ3TkxrBBwY',
    appId: '1:946653516976:android:ca8132ebf82af49f311775',
    messagingSenderId: '946653516976',
    projectId: 'instaface-cfa00',
    storageBucket: 'instaface-cfa00.appspot.com',
  );
}
